import React from 'react'
import { Helmet } from 'react-helmet-async'
import Header from 'components/LandingPage/Header'
import Footer from 'components/LandingPage/Footer'

const PageFrame = ({ title, description, children }) => (
  <div className='full-container'>
    <Helmet><title>{title} | GrantMaestro</title><meta name='description' content={description} /><meta name='robots' content='noindex,follow' /></Helmet>
    <Header />
    <main id='main-content' tabIndex='-1' style={{ background: '#f7fafc', padding: '104px 20px 72px' }}>
      <article style={{ maxWidth: 920, margin: '0 auto', background: '#fff', borderRadius: 12, padding: '48px', boxShadow: '0 2px 16px rgba(15, 23, 42, 0.08)', color: '#243447', lineHeight: 1.7 }}>{children}</article>
    </main>
    <Footer />
  </div>
)
const Heading = ({ id, children }) => <h2 id={id} style={{ color: '#001A8B', fontSize: 22, marginTop: 36 }}>{children}</h2>
const Notice = ({ children }) => <p style={{ padding: '14px 16px', borderLeft: '4px solid #1267D8', background: '#EAF4FF', color: '#173A60' }}>{children}</p>

export const PrivacyPolicyPage = () => (
  <PageFrame title='Privacy Policy' description='GrantMaestro privacy policy, data-handling and service-provider summary.'>
    <p style={{ color: '#64748b', marginBottom: 8 }}>Last updated: 6 October 2026</p><h1 style={{ color: '#001A8B', fontSize: 36, marginTop: 0 }}>Privacy Policy</h1>
    <Notice>GrantMaestro is a grant-management platform. This policy explains how personal information is handled on the website and within an organisation’s workspace. It is not a claim that every service provider processes data only in Australia.</Notice>
    <Heading>Information we collect</Heading><p>We collect account and organisation information provided during registration and use, including contact details, role details, subscription information and workspace content such as grant records, notes, tasks, uploaded documents and support requests. We also collect limited technical and security information, including browser, device, IP address and log information.</p>
    <Heading>How we use information</Heading><p>We use information to provide, secure and support GrantMaestro; administer accounts and subscriptions; send requested service communications; maintain audit trails; investigate misuse or incidents; and improve the product. We do not sell personal information.</p>
    <Heading>Hosting, service providers and international processing</Heading><p>GrantMaestro’s core application hosting may be operated on Australian infrastructure. Other functions can involve carefully selected third parties, including email delivery, payment processing, file storage, security verification and optional AI-assisted drafting or analysis. Those providers may process information in locations outside Australia or New Zealand, subject to their own contractual, privacy and security terms.</p><p>We minimise the information sent to optional AI features and do not send lead-magnet contact details or free-text answers to the readiness-analysis workflow. Organisation administrators remain responsible for deciding whether users are authorised to use optional AI features with their organisation’s information.</p><p>For a current service-provider, processing-location or safeguards summary relevant to your proposed use, submit a <a href='/contact?topic=privacy'>privacy enquiry</a>. We review this summary when a material provider or processing arrangement changes.</p>
    <Heading>Security, retention and deletion</Heading><p>We apply reasonable technical and organisational safeguards, including access controls, encrypted credential storage and audit-oriented product design. No online service can guarantee absolute security. We retain information for the period needed to provide the service, meet legal obligations, resolve disputes, maintain backups and protect the service. On termination, account access ends in accordance with the applicable subscription terms; organisations should request an export before access ends. Deletion from active systems and backup cycles is managed according to operational, legal and security requirements.</p>
    <Heading>Your organisation’s responsibilities</Heading><p>Customer organisations are responsible for deciding which users receive access, ensuring their grant data is accurate and lawful to process, and responding to requests from their staff, applicants or other data subjects where applicable.</p>
    <Heading>Access, correction and privacy enquiries</Heading><p>You may request access to or correction of personal information, ask a privacy question, or raise a concern through our <a href='/contact?topic=privacy'>dedicated privacy enquiry form</a>. We may need to verify identity and authority before responding. Do not include passwords, card details, secret keys or other credentials.</p>
    <Heading>Updates</Heading><p>We may update this policy as GrantMaestro evolves. Material changes will be published on this page with an updated date.</p>
  </PageFrame>
)

export const SupportPage = () => (
  <PageFrame title='Support' description='GrantMaestro support, escalation and account assistance.'>
    <p style={{ color: '#64748b', marginBottom: 8 }}>GrantMaestro Support</p><h1 style={{ color: '#001A8B', fontSize: 36, marginTop: 0 }}>How can we help?</h1>
    <p>For account access, billing, subscription, grants workspace or technical support, use the secure <a href='/contact?topic=support'>support enquiry form</a>. Include your organisation name, the email associated with the account, the page or action involved, displayed error text and the approximate time of the issue.</p>
    <Heading>Support target and escalation</Heading><p>Support requests are reviewed during Australian Eastern Time business hours on business days. Response targets are not contractual service-level agreements and do not replace any separate Enterprise arrangement in an executed agreement.</p><table style={{ width: '100%', borderCollapse: 'collapse', margin: '16px 0' }}><thead><tr><th scope='col' style={{ textAlign: 'left', borderBottom: '2px solid #B9D1E9', padding: '8px' }}>Plan</th><th scope='col' style={{ textAlign: 'left', borderBottom: '2px solid #B9D1E9', padding: '8px' }}>Initial response target</th></tr></thead><tbody><tr><th scope='row' style={{ textAlign: 'left', borderBottom: '1px solid #D9E4F0', padding: '8px' }}>Starter</th><td style={{ borderBottom: '1px solid #D9E4F0', padding: '8px' }}>Within 2 business days</td></tr><tr><th scope='row' style={{ textAlign: 'left', borderBottom: '1px solid #D9E4F0', padding: '8px' }}>Pro</th><td style={{ borderBottom: '1px solid #D9E4F0', padding: '8px' }}>Within 1 business day</td></tr><tr><th scope='row' style={{ textAlign: 'left', padding: '8px' }}>Enterprise</th><td style={{ padding: '8px' }}>Priority review, target within 1 business day</td></tr></tbody></table><ul><li><strong>Urgent service interruption:</strong> state “Urgent service interruption” in the form subject and describe the organisation-wide impact.</li><li><strong>Material impairment:</strong> describe the blocked workflow, affected grant records and any workaround.</li><li><strong>Standard request:</strong> include the grant name, page, action and expected outcome.</li></ul>
    <Heading>Get started in your first week</Heading><p>Begin by adding one live or target funding opportunity, confirming its deadline and assigning an accountable officer. Invite the grants, finance and project staff who need to contribute. Use the task work queue for the first actions, and use the Acquittal Centre when an awarded grant has evidence, reconciliation or submission requirements.</p>
    <Heading>Account access and security</Heading><p>If you cannot sign in, use the password-reset option first. Invited team members may be required to set a new password before accessing their workspace. Do not submit passwords, payment-card details, secret keys or other credentials. We will never ask for your password.</p>
  </PageFrame>
)

export const TermsOfServicePage = () => (
  <PageFrame title='Terms of Service' description='GrantMaestro platform terms, billing, trial, renewal and cancellation information.'>
    <p style={{ color: '#64748b', marginBottom: 8 }}>Last updated: 6 October 2026</p><h1 style={{ color: '#001A8B', fontSize: 36, marginTop: 0 }}>Terms of Service</h1>
    <p>These terms govern use of the GrantMaestro website and grant-management platform. By creating an account or using the service, you agree to these terms on behalf of yourself and, where applicable, the organisation you represent.</p>
    <Heading>Service</Heading><p>GrantMaestro provides tools to help organisations organise grant opportunities, tasks, records, documents, reporting and collaboration. The service supports administrative work; it does not provide legal, financial, tax, funding or professional advice, and it does not guarantee grant eligibility, funding outcomes or compliance results.</p>
    <Heading>Accounts and access</Heading><p>Organisation administrators are responsible for maintaining accurate account details, protecting credentials, assigning appropriate roles and promptly removing access for former staff or contributors. Users must not share accounts or attempt to access information outside their authorised organisation.</p>
    <Heading>Customer content</Heading><p>Your organisation retains ownership of content it enters into GrantMaestro. You grant GrantMaestro the limited right to host, process and display that content only as necessary to operate, secure, support and improve the service. You are responsible for ensuring you have the necessary rights and authority to provide that content.</p>
    <Heading id='billing'>Billing, trial, renewal and cancellation</Heading><p><strong>Trial.</strong> GrantMaestro currently offers a 14-day trial with no card required at registration. A no-card trial does not automatically convert to a paid subscription. To begin a paid subscription, an authorised organisation administrator must complete the applicable checkout or other agreed payment process.</p><p><strong>Prices and billing period.</strong> Current plan prices and inclusions are displayed on the Pricing page and at checkout. Monthly plans are billed monthly; annual plans are billed once per year and are advertised as two months free (the cost of ten monthly payments for twelve months of access). Prices are shown in Australian dollars. Any applicable taxes are presented in the checkout or invoice process.</p><p><strong>Renewal and payment authority.</strong> Where a paid subscription is configured to renew, the relevant payment provider’s checkout terms, payment authority and renewal information apply. We will present the material payment terms before checkout. If recurring payment arrangements or plan prices change, we will provide notice required by law or the applicable agreement before the change takes effect.</p><p><strong>Cancellation.</strong> An organisation administrator may request cancellation through the <a href='/contact?topic=support'>support enquiry form</a>. Unless another agreement states otherwise, cancellation takes effect at the end of the current paid period; access remains available until then. Fees already paid are not refunded or credited except where required by law or expressly agreed in writing.</p><p><strong>After cancellation.</strong> Before the paid period ends, organisations should request an export of the content they need to retain. Access ends at the end of the paid period. We manage retained information and deletion in line with the Privacy Policy, operational backup cycles and legal obligations.</p>
    <Heading>Acceptable use</Heading><p>You must use the service lawfully, keep submitted information accurate, respect the rights of others and not interfere with the security or availability of GrantMaestro. You must not upload malicious files, attempt unauthorised access or use the service to process information unlawfully.</p>
    <Heading>Availability and liability</Heading><p>We aim to provide a reliable service but cannot guarantee uninterrupted availability. To the extent permitted by law, GrantMaestro’s liability is limited to the fees paid for the affected service during the relevant period. Nothing in these terms excludes rights that cannot be excluded under applicable law.</p>
    <Heading>Changes and contact</Heading><p>We may update these terms as the service evolves. Continued use after an updated version takes effect constitutes acceptance of the updated terms. Questions can be sent through our <a href='/contact'>contact form</a>.</p>
  </PageFrame>
)
